#include <iostream>
#include <random>
#include <climits>
#include <cstdlib>
int tmpChar[16] = {0};

void inline printVar(unsigned var) {
    int pos = 0;
    while (var != 0) {
        tmpChar[pos++] = var % 10 + '0';
        var /= 10;
    }
    for (; pos != 0;)
        putchar_unlocked(tmpChar[--pos]);
    putchar_unlocked(' ');
}

int main() {
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    const unsigned MaxNum = UINT_MAX;
    std::uniform_int_distribution<unsigned> dis(0, MaxNum);
    unsigned count = 250000000;
    for (int n=0; n<count; ++n) {
        //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
        printVar(dis(gen));
    }
    return 0;
}